# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frontloop < Formula
  desc "CLI for managing frontloop task queues"
  homepage "https://github.com/ohare93/frontloop"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ohare93/frontloop/releases/download/v1.0.0/frontloop_1.0.0_darwin_amd64.tar.gz"
      sha256 "4a77ea364bcc86fd7eb484d70798ead0e13acc9322641fbfd59fc2bf6f256cab"

      define_method(:install) do
        bin.install "fl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ohare93/frontloop/releases/download/v1.0.0/frontloop_1.0.0_darwin_arm64.tar.gz"
      sha256 "490e46df469b46697515b68c829e4aba9dce2a67cded7a35d343c1b65115c5aa"

      define_method(:install) do
        bin.install "fl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/frontloop/releases/download/v1.0.0/frontloop_1.0.0_linux_amd64.tar.gz"
      sha256 "ce12fadf7cc31870b06cd01eaed178e31f09028f59dc579aecc5b001eb31cb38"
      define_method(:install) do
        bin.install "fl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ohare93/frontloop/releases/download/v1.0.0/frontloop_1.0.0_linux_arm64.tar.gz"
      sha256 "ae5f5f4db4e320fb6e1aeb97549013c8e3885df49cf92a94fc583a7ca08091ef"
      define_method(:install) do
        bin.install "fl"
      end
    end
  end

  test do
    system "#{bin}/fl", "--version"
  end
end
